//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bot.GetByLink.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ClientResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClientResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bot.GetByLink.Common.Resources.ClientResource", typeof(ClientResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🇷🇺 Не удалось получить ресурс по ссылке
        ///🇺🇸 Failed to get resource by reference.
        /// </summary>
        internal static string FailedGetResource {
            get {
                return ResourceManager.GetString("FailedGetResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🇷🇺 *Справка и описание бота*
        ///
        ///*Список команд:*
        ////help - справка и описание бота.
        ////chatInfo - информация о чате в котором ввели команду.
        ///
        ///*Описание бота:*
        ///Данный бот позволяет получить контент в &quot;чистом&quot; виде по ссылке поста.
        ///Ссылка на бота в гите: [bot-get-by-link](https://github.com/AnatoliyCh/bot-get-by-link)
        ///В текущий момент бот работает с постами [VK](https://vk.com) и [Reddit](https://www.reddit.com/).
        ///
        ///*Особенности бота:*
        /// 1. Если в посте много контента (пример: альбом VK) бот будет присы [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpCommand {
            get {
                return ResourceManager.GetString("HelpCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🇷🇺 Неправильная команда
        ///🇺🇸 Wrong command.
        /// </summary>
        internal static string WrongCommand {
            get {
                return ResourceManager.GetString("WrongCommand", resourceCulture);
            }
        }
    }
}
