name: dotnet-build

on:
    push:
        branches: ["dev", "master"]
    pull_request:
        branches: ["dev", "master"]

jobs:
    build-release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup .NET
              uses: actions/setup-dotnet@v2
              with:
                  dotnet-version: 6.0.x

            - name: Restore dependencies
              run: dotnet restore

            - name: Setup ReSharper Command Line Tools
              uses: goit/setup-resharper@v2.0.1
              with:
                  version: "2021.2"

            - name: InspectCode
              run: |
                  dotnet tool restore
                  dotnet jb inspectcode Bot.GetByLink.sln

            - name: Build
              run: dotnet build --configuration Release --no-restore
